services:
  kafka:
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092       
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  postgres:
    container_name: pismo-postgres-db
    image: postgres:16
    environment:
      POSTGRES_DB: pismo-database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  zookeeper:
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
    image: confluentinc/cp-zookeeper:7.5.0

  processor:
    build: .
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_TOPIC: events
      KAFKA_GROUP_ID: processor-group-1
      KAFKA_BROKERS: kafka:9092
      DATABASE_URL: postgres://username:password@postgres:5432/pismo-database?sslmode=disable
    

    
    